# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Twisty.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'Twisty.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cTwisty.proto\x12\x06twisty\"\x8c\x01\n\x0bTwistyState\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x11\n\tepisodeID\x18\x02 \x01(\t\x12\x12\n\npuzzleName\x18\x07 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05steps\x18\x04 \x01(\x05\x12\x11\n\tobtmMoves\x18\x05 \x01(\x05\x12\x12\n\nvalidMoves\x18\x06 \x03(\t\"\x1c\n\x0cTwistyAction\x12\x0c\n\x04move\x18\x01 \x01(\t\"C\n\x0cTwistyResult\x12\r\n\x05state\x18\x01 \x01(\t\x12$\n\x06signal\x18\x02 \x01(\x0e\x32\x14.twisty.TwistySignal*/\n\x0cTwistySignal\x12\x0c\n\x08\x43ONTINUE\x10\x00\x12\x07\n\x03WIN\x10\x01\x12\x08\n\x04LOSE\x10\x02\x42\x30\n,dev.aisandbox.server.simulation.twisty.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Twisty_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,dev.aisandbox.server.simulation.twisty.protoP\001'
  _globals['_TWISTYSIGNAL']._serialized_start=266
  _globals['_TWISTYSIGNAL']._serialized_end=313
  _globals['_TWISTYSTATE']._serialized_start=25
  _globals['_TWISTYSTATE']._serialized_end=165
  _globals['_TWISTYACTION']._serialized_start=167
  _globals['_TWISTYACTION']._serialized_end=195
  _globals['_TWISTYRESULT']._serialized_start=197
  _globals['_TWISTYRESULT']._serialized_end=264
# @@protoc_insertion_point(module_scope)
