# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Maze.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'Maze.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMaze.proto\x12\x04maze\"\x83\x01\n\tMazeState\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x11\n\tepisodeID\x18\x02 \x01(\t\x12\x0e\n\x06startX\x18\x03 \x01(\x05\x12\x0e\n\x06startY\x18\x04 \x01(\x05\x12\x11\n\tmovesLeft\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\"0\n\nMazeAction\x12\"\n\tdirection\x18\x01 \x01(\x0e\x32\x0f.maze.Direction\"\x99\x01\n\nMazeResult\x12\x0e\n\x06startX\x18\x01 \x01(\x05\x12\x0e\n\x06startY\x18\x02 \x01(\x05\x12\"\n\tdirection\x18\x03 \x01(\x0e\x32\x0f.maze.Direction\x12\x0c\n\x04\x65ndX\x18\x04 \x01(\x05\x12\x0c\n\x04\x65ndY\x18\x05 \x01(\x05\x12\x11\n\tstepScore\x18\x06 \x01(\x01\x12\x18\n\x10\x61\x63\x63umulatedScore\x18\x07 \x01(\x01*5\n\tDirection\x12\t\n\x05NORTH\x10\x00\x12\t\n\x05SOUTH\x10\x01\x12\x08\n\x04\x45\x41ST\x10\x02\x12\x08\n\x04WEST\x10\x03\x42.\n*dev.aisandbox.server.simulation.maze.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Maze_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*dev.aisandbox.server.simulation.maze.protoP\001'
  _globals['_DIRECTION']._serialized_start=360
  _globals['_DIRECTION']._serialized_end=413
  _globals['_MAZESTATE']._serialized_start=21
  _globals['_MAZESTATE']._serialized_end=152
  _globals['_MAZEACTION']._serialized_start=154
  _globals['_MAZEACTION']._serialized_end=202
  _globals['_MAZERESULT']._serialized_start=205
  _globals['_MAZERESULT']._serialized_end=358
# @@protoc_insertion_point(module_scope)
