# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HighLowCards.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'HighLowCards.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12HighLowCards.proto\x12\x0chighlowcards\"n\n\x11HighLowCardsState\x12\x11\n\tcardCount\x18\x01 \x01(\x05\x12\x11\n\tdealtCard\x18\x02 \x03(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x12$\n\x06signal\x18\x04 \x01(\x0e\x32\x14.highlowcards.Signal\"@\n\x11HighLowCardAction\x12+\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1b.highlowcards.HighLowChoice*\"\n\rHighLowChoice\x12\x08\n\x04HIGH\x10\x00\x12\x07\n\x03LOW\x10\x01*\x1d\n\x06Signal\x12\t\n\x05RESET\x10\x00\x12\x08\n\x04PLAY\x10\x01\x42\x36\n2dev.aisandbox.server.simulation.highlowcards.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HighLowCards_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2dev.aisandbox.server.simulation.highlowcards.protoP\001'
  _globals['_HIGHLOWCHOICE']._serialized_start=214
  _globals['_HIGHLOWCHOICE']._serialized_end=248
  _globals['_SIGNAL']._serialized_start=250
  _globals['_SIGNAL']._serialized_end=279
  _globals['_HIGHLOWCARDSSTATE']._serialized_start=36
  _globals['_HIGHLOWCARDSSTATE']._serialized_end=146
  _globals['_HIGHLOWCARDACTION']._serialized_start=148
  _globals['_HIGHLOWCARDACTION']._serialized_end=212
# @@protoc_insertion_point(module_scope)
