# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Bandit.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'Bandit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x42\x61ndit.proto\x12\x06\x62\x61ndit\"i\n\x0b\x42\x61nditState\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x11\n\tepisodeID\x18\x02 \x01(\t\x12\x13\n\x0b\x62\x61nditCount\x18\x03 \x01(\x05\x12\x11\n\tpullCount\x18\x04 \x01(\x05\x12\x0c\n\x04pull\x18\x05 \x01(\x05\"\x1b\n\x0c\x42\x61nditAction\x12\x0b\n\x03\x61rm\x18\x01 \x01(\x05\"J\n\x0c\x42\x61nditResult\x12\x0b\n\x03\x61rm\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x1e\n\x06signal\x18\x03 \x01(\x0e\x32\x0e.bandit.Signal*!\n\x06Signal\x12\x0c\n\x08\x43ONTINUE\x10\x00\x12\t\n\x05RESET\x10\x01\x42\x30\n,dev.aisandbox.server.simulation.bandit.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Bandit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,dev.aisandbox.server.simulation.bandit.protoP\001'
  _globals['_SIGNAL']._serialized_start=236
  _globals['_SIGNAL']._serialized_end=269
  _globals['_BANDITSTATE']._serialized_start=24
  _globals['_BANDITSTATE']._serialized_end=129
  _globals['_BANDITACTION']._serialized_start=131
  _globals['_BANDITACTION']._serialized_end=158
  _globals['_BANDITRESULT']._serialized_start=160
  _globals['_BANDITRESULT']._serialized_end=234
# @@protoc_insertion_point(module_scope)
