# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Mine.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'Mine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nMine.proto\x12\x04mine\"p\n\tMineState\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x11\n\tepisodeID\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x11\n\tflagsLeft\x18\x05 \x01(\x05\x12\x0b\n\x03row\x18\x06 \x03(\t\"D\n\nMineAction\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12 \n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x10.mine.FlagAction\"f\n\nMineResult\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12 \n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x10.mine.FlagAction\x12 \n\x06signal\x18\x04 \x01(\x0e\x32\x10.mine.MineSignal*%\n\nFlagAction\x12\x0e\n\nPLACE_FLAG\x10\x00\x12\x07\n\x03\x44IG\x10\x01*-\n\nMineSignal\x12\x0c\n\x08\x43ONTINUE\x10\x00\x12\x07\n\x03WIN\x10\x01\x12\x08\n\x04LOSE\x10\x02\x42.\n*dev.aisandbox.server.simulation.mine.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Mine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*dev.aisandbox.server.simulation.mine.protoP\001'
  _globals['_FLAGACTION']._serialized_start=308
  _globals['_FLAGACTION']._serialized_end=345
  _globals['_MINESIGNAL']._serialized_start=347
  _globals['_MINESIGNAL']._serialized_end=392
  _globals['_MINESTATE']._serialized_start=20
  _globals['_MINESTATE']._serialized_end=132
  _globals['_MINEACTION']._serialized_start=134
  _globals['_MINEACTION']._serialized_end=202
  _globals['_MINERESULT']._serialized_start=204
  _globals['_MINERESULT']._serialized_end=306
# @@protoc_insertion_point(module_scope)
