# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CoinGame.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'CoinGame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x43oinGame.proto\x12\x08\x63oingame\"k\n\rCoinGameState\x12\x11\n\tsessionID\x18\x01 \x01(\t\x12\x11\n\tepisodeID\x18\x02 \x01(\t\x12\x10\n\x08rowCount\x18\x03 \x01(\x05\x12\x11\n\tcoinCount\x18\x04 \x03(\x05\x12\x0f\n\x07maxPick\x18\x05 \x01(\x05\":\n\x0e\x43oinGameAction\x12\x13\n\x0bselectedRow\x18\x01 \x01(\x05\x12\x13\n\x0bremoveCount\x18\x02 \x01(\x05\":\n\x0e\x43oinGameResult\x12(\n\x06status\x18\x01 \x01(\x0e\x32\x18.coingame.CoinGameSignal*-\n\x0e\x43oinGameSignal\x12\x07\n\x03WIN\x10\x00\x12\x08\n\x04PLAY\x10\x01\x12\x08\n\x04LOSE\x10\x02\x42\x32\n.dev.aisandbox.server.simulation.coingame.protoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CoinGame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.dev.aisandbox.server.simulation.coingame.protoP\001'
  _globals['_COINGAMESIGNAL']._serialized_start=257
  _globals['_COINGAMESIGNAL']._serialized_end=302
  _globals['_COINGAMESTATE']._serialized_start=28
  _globals['_COINGAMESTATE']._serialized_end=135
  _globals['_COINGAMEACTION']._serialized_start=137
  _globals['_COINGAMEACTION']._serialized_end=195
  _globals['_COINGAMERESULT']._serialized_start=197
  _globals['_COINGAMERESULT']._serialized_end=255
# @@protoc_insertion_point(module_scope)
